import type { CardKind, Item, ItemType } from '@prisma/client';

// Shape of the jsonb `content` column for each item type. Declared as
// `type` (not `interface`) so Prisma accepts them as JSON values.
export type QuoteContent = {
  text: string;
  author: string | null;
  source: string | null;
};

export type VocabularyContent = {
  word: string; // English
  translation: string; // French
  example: string | null; // example sentence, in English
};

export type MindMapNode = {
  id: string; // generated by the client, stable across edits
  parentId: string | null; // null for the root, and only for the root
  label: string;
  position: { x: number; y: number }; // where the editor draws it
};

/**
 * A mind map is a tree. Storing each node's parent (rather than a list of
 * edges) makes "one parent per node" true by construction; what's left to
 * check is done by validateMindMap() (mind-maps/mind-map-tree.ts).
 */
export type MindMapContent = {
  nodes: MindMapNode[];
};

export type ContentByType = {
  Quote: QuoteContent;
  Vocabulary: VocabularyContent;
  MindMap: MindMapContent;
};

/** Runtime list of item types (for validation), in sync with the Prisma enum. */
export const ITEM_TYPES = {
  Quote: 'Quote',
  Vocabulary: 'Vocabulary',
  MindMap: 'MindMap',
} as const satisfies Record<ItemType, ItemType>;

/**
 * One card to create for an item. `nodeId` identifies which part of the
 * item the card asks about when there can be several cards of the same
 * kind (the branches of a mind map).
 */
export type CardSlot = { kind: CardKind; nodeId: string | null; delayDays: number };

/** Identifies a slot, to compare the cards an item has with those it should have. */
export const slotKey = ({ kind, nodeId }: { kind: CardKind; nodeId: string | null }) => `${kind}:${nodeId ?? ''}`;

/**
 * Cards an item should have, given its content.
 *
 * - a quote: one card;
 * - a vocabulary word: one card per direction, the reverse one starting a
 *   day later so the two sides of the same word aren't asked back to back
 *   (a simple take on Anki's "burying" of sibling cards);
 * - a mind map: one card per branch (child of the root), staggered by one
 *   day each for the same reason. It changes when the map is edited.
 */
export function cardSlots<T extends ItemType>(type: T, content: ContentByType[T]): CardSlot[] {
  switch (type) {
    case 'Quote':
      return [{ kind: 'QuoteRecall', nodeId: null, delayDays: 0 }];
    case 'Vocabulary':
      return [
        { kind: 'EnglishToFrench', nodeId: null, delayDays: 0 },
        { kind: 'FrenchToEnglish', nodeId: null, delayDays: 1 },
      ];
    case 'MindMap': {
      const { nodes } = content as MindMapContent;
      const root = nodes.find((node) => node.parentId === null);
      return nodes
        .filter((node) => root && node.parentId === root.id)
        .map((branch, index) => ({ kind: 'BranchRecall', nodeId: branch.id, delayDays: index }));
    }
    default:
      throw new Error(`Unknown item type: ${String(type)}`);
  }
}

/** Typed view of an item's content (the database only knows it's JSON). */
export function contentOf<T extends ItemType>(item: Pick<Item, 'content'> & { type: T }): ContentByType[T] {
  return item.content as unknown as ContentByType[T];
}
