import { Transform, Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsNotEmpty,
  IsNumber,
  IsString,
  Matches,
  MaxLength,
  ValidateIf,
  ValidateNested,
} from 'class-validator';

export const MAX_NODES = 200;

class PositionDto {
  @IsNumber()
  x!: number;

  @IsNumber()
  y!: number;
}

class MindMapNodeDto {
  /** Generated by the client (crypto.randomUUID()), stable across edits. */
  @IsString()
  @Matches(/^[\w-]{1,64}$/)
  id!: string;

  /** Null for the root only. */
  @ValidateIf((_, value) => value !== null)
  @IsString()
  parentId!: string | null;

  // Trimmed before validation, so that "   " is rejected as empty.
  @Transform(({ value }: { value: unknown }) => (typeof value === 'string' ? value.trim() : value))
  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  label!: string;

  // Without @Type, class-transformer leaves nested objects as plain
  // objects: the ValidationPipe would neither validate them nor strip their
  // unknown properties (whitelist).
  @ValidateNested()
  @Type(() => PositionDto)
  position!: PositionDto;
}

/**
 * Body of POST /mind-maps and PUT /mind-maps/:id: the whole tree is sent
 * each time (the editor saves the map as a whole). Each node is validated
 * here; the tree shape (one root, no cycle...) by validateMindMap().
 */
export class SaveMindMapDto {
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(MAX_NODES)
  @ValidateNested({ each: true })
  @Type(() => MindMapNodeDto)
  nodes!: MindMapNodeDto[];
}
